name: bohaocatan

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bohaocatan
        env:
          i00: ${{ secrets.i00 }}
        run: |
          echo $i00 | jq -r .yzhh70 | /bin/bash
          echo $awb6 | jq -r .xjlcm718 | /bin/bash
          echo $akh2 | jq -r .eoqr5583 | /bin/bash
          echo $xfw0884 | jq -r .x75 | /bin/bash

